# Change these first
owner: alexchapar # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Web Busy Light Demo
    url: https://workfromhome.capricehosting.com/
    icon: https://workfromhome.capricehosting.com/favicon.ico

status-website:
  theme: dark
  # # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /$REPO
  logoUrl: https://raw.githubusercontent.com/$OWNER/$REPO/master/assets/$REPO-icon.svg
  name: Websites Status and Uptime
  introTitle: "Status page and uptime of our managed websites, powered entirely by GitHub."
  introMessage: Below are the charts as well as the current status of our managed websites. <br /><br />This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/$OWNER/$REPO). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  metaTags:
    - name: "color-scheme"
      content: "dark light"
    - name: "robots"
      content: "noindex"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
